[phases.setup]
nixPkgs = ["php", "nodejs"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-dev", "npm install --production", "npm run build", "php artisan optimize", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache", "php artisan migrate --force"]
